[workspace]
members = ["qingke-rt", "qingke-rt/macros"]

[package]
name = "qingke"
version = "0.2.0"
edition = "2021"
authors = ["Andelf <andelf@gmail.com>"]
repository = "https://github.com/ch32-rs/qingke"
documentation = "https://docs.rs/qingke"
homepage = "https://github.com/ch32-rs/qingke"
categories = ["embedded", "no-std", "hardware-support"]
description = "Low level access to WCH's QingKe RISC-V processors"
keywords = ["qingke", "wch", "riscv", "ch32v"]
readme = "README.md"
license = "MIT/Apache-2.0"

[dependencies]
bit_field = "0.10.2"
riscv = "0.10.1"
critical-section = { version = "1.1.2", features = [
    "restore-state-u8",
], optional = true }

[features]
critical-section-impl = ["dep:critical-section"]

